### ISSUE TITLE
Suggestion to improve the tool

### ISSUE THREAD

**Issue by apovetkin** [niklaskallander/vs-unobtrusive-code#1]
First of all thanks for the great tool for Visual Studio. I like your tool.

I couldn't find how to create suggestion in GitHub and decided to create an issue.

Suggestion or Issue: 
When I need to read comments I have to go to settings and change them. Is it possible to make shortcut like you did Alt + Q for collapsing, but for make opacity 100% and back to 25% ?

Very appreciated if you can do it.

Thanks,
Alex

**Comment by niklaskallander** [comment]
@apovetkin thanks for the feedback!

I'm all for that and I'll definitely have a look at it. However, the settings for opacity is only loaded during opening of a document (when `ClassificationFormatDefinition`s are loaded by VS), I think. If this is the case, the document will have to be reloaded (sub-optimal), but maybe there's a neat undocumented solution for this, like for many other things. (:

Have you considered just always having 75-100% opacity for comments and let the outlining feature do the heavy-lifting?

Thanks!

**Comment by apovetkin** [comment]
--Have you considered just always having 75-100% opacity
It was just an example. Any solution to read comments would be acceptable. 
For example: 
1. Tooltip
2. Select comment makes more readable (actually I can try to play with this option in fonts settings)

If you have any idea how to simple see comments would be nice.

Any way I like your tool. 5+

Thanks,
Alex

**Comment by apovetkin** [comment]
Actually Color and Fonts helped to make readable comments.

Many thanks for the great tool.

Recommend.

Thanks,
Alex

**Comment by niklaskallander** [comment]
@apovetkin I've just released a new version which introduces an opacity toggle feature (full/configuration). Check it out! (:

Thanks!
