### ISSUE TITLE
VS2019 and VS2022 show error message -> package is not loaded correctly

### ISSUE THREAD

**Issue by apovetkin** [niklaskallander/vs-unobtrusive-code#12]
Recently noticed that the tool doesn't want to load properly

  <entry>
    <record>2606</record>
    <time>2022/03/18 02:19:47.814</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Performance warning: String load failed. Pkg:{377F72AD-751E-4B9A-863A-2CD3B7F0A034} (UnobtrusiveCodePackage) LANG:0409 ID:0&#x000D;&#x000A;</description>
  </entry>

**Comment by niklaskallander** [comment]
Hi, thanks for the report!

I’ll see if I can manage time to look into this over the weekend.

**Comment by apovetkin** [comment]
Hi Niklas,

Thanks for respond, I downloaded prev version and it works pretty well with vs2019, not 2022.

Anyway thanks for the great tool.

Alex

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TheEmbracedOne** [comment]
Unfortunately, it does not work for me on 2019 (version 16.11.27, .NET 4.8.09032). I'd greatly appreciate some help with this, I'd love to use this extension.

On launching Visual Studio I get the following error:
![image](https://github.com/niklaskallander/vs-unobtrusive-code/assets/16197906/fb49f883-5a8f-42aa-a963-7e0008d3efdc)

the entry in question:
<entry>
    <record>741</record>
    <time>2023/06/19 01:14:50.315</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [UnobtrusiveCodePackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{377F72AD-751E-4B9A-863A-2CD3B7F0A034}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by niklaskallander** [comment]
Not planning any further support for VS 2019, sorry.
