### ISSUE TITLE
Dimming opacity toggle key resets on VS restart

### ISSUE THREAD

**Issue by IneedHelp** [niklaskallander/vs-unobtrusive-code#16]
Hello! Amazing extension, really great job.

There's a minor issue I've noticed, the "Dimming opacity toggle key" gets reset to the default value when restarting Visual Studio 2022, regardless of VS version. It's a little bit inconvenient because I have to set it to my personal preference every time I start VS.

Do you think it's something that can be fixed? Thank you!

**Comment by ryanbuening** [comment]
Same here. [Here is the commit](https://github.com/niklaskallander/vs-unobtrusive-code/commit/6848696c74aa56ebe7737056c62c5a47eaf5ad98) that added this feature. I'm not too familiar with VS extensions and how/where they save option values though...

**Comment by IneedHelp** [comment]
Unfortunately I have a feeling that this extension is abandoned :( and a bit unlikely we'll hear from the author any time soon.

**Comment by niklaskallander** [comment]
@IneedHelp thanks for the report! It's not exactly abandoned, but I'm not actively working on it. It fits my needs, so I don't touch it unless I have to.

Have it always behaved like this for you? I'm not experiencing this particular issue myself, although I should have used better defaults when I built it...

**Comment by IneedHelp** [comment]
> @IneedHelp thanks for the report! It's not exactly abandoned, but I'm not actively working on it. It fits my needs, so I don't touch it unless I have to.
> 
> Have it always behaved like this for you? I'm not experiencing this particular issue myself, although I should have used better defaults when I built it...

Hello :D I apologize, it honestly looked like a forgotten gem.
Yes, I have always had this issue and I've been using it for about a couple years now throughout regular and preview VS2022 versions.
I just recently decided to report the issue, but I pretty much manually changed the option every time after a VS restart. It always defaults to the LeftShift.

Thank you for taking this into consideration and sorry for the late reply.

**Comment by niklaskallander** [comment]
@IneedHelp I'm struggling to get things to work in my environment. New computer and new versions of everything... it does not bode well, but I'll see what I can manage.

**Comment by niklaskallander** [comment]
@IneedHelp @ryanbuening should work now with the new version, but the fix seem to have made all current options corrupt so you may have to reset them (I had to).

**Comment by IneedHelp** [comment]
Thanks a lot for taking the time to make the fix and for the creation of this useful extension!

**Comment by niklaskallander** [comment]
Closing this, as I assume it's fixed now. Yay!
