### ISSUE TITLE
The 'UnobtrusiveCodePackage' package did not load correctly

### ISSUE THREAD

**Issue by SinonTheCat** [niklaskallander/vs-unobtrusive-code#17]
SetSite failed for package [UnobtrusiveCodePackage] 
Source: 'UnobtrusiveCode' Description: Die Datei oder Assembly "Microsoft.VisualStudio.Threading, Version=17.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
System.IO.FileNotFoundException: Die Datei oder Assembly "Microsoft.VisualStudio.Threading, Version=17.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
File name: 'Microsoft.VisualStudio.Threading, Version=17.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at UnobtrusiveCode.UnobtrusiveCodePackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)3

Microsoft Visual Studio Professional 2022
Version 17.7.5
VisualStudio.17.Release/17.7.5+34202.233
Microsoft .NET Framework
Version 4.8.09032

**Comment by niklaskallander** [comment]
@SinonTheCat what version of VS are you using? Just wondering if you may have to update it. Are there updates available?

**Comment by SinonTheCat** [comment]
Hi. It's all in the issue. VS 2022, extension freshly installed.
I'm opening a solution that also contains C++  code, but that should not bother the extension.
Is it only compatible with the latest and greatest .NET framework installed?
I'll look, if an update for Vs is available.

Harald Rafetseder
________________________________

**Comment by niklaskallander** [comment]
@SinonTheCat Sorry, I just read a bunch of German/whatever and got blind. 😄

I hope an upgrade of VS sorts it out for you. I just recently updated the extension to use .NET Framework 4.8 (in order to support the use of Community.VisualStudio.Toolkit).

It works fine on both my computers (personal and at work).

Let me know how it goes, thanks! 😊

**Comment by niklaskallander** [comment]
Closing this.
