### ISSUE TITLE
key binding

### ISSUE THREAD

**Issue by KKacer** [niklaskallander/vs-unobtrusive-code#3]
Hello Niklas,
Thanks for the great extension.
It was working at the first setup. (for me, needed to set the key manually)
Though, after setting up R#, a reset of VS key-bindings,
Couldn't find the assigned name in the key mappings to re-assign it.
several uninstall and installing also didn't help.

**Comment by niklaskallander** [comment]
Thanks for the report! (:

The command id should be “EditorContextMenus.CodeWindow.CollapseUncollapseObtrusiveCodeOutliningRegions“, is it missing altogether?

**Comment by niklaskallander** [comment]
@KKacer I've tried to repro this (although I haven't tried the whole R# thing - I don't have a license, and last I had a license, VS was better of without it anyway). Resetting VS key-bindings refuses to mess anything up on my regular VS installation and the same goes for the debug instance. I'll try it at work tomorrow.

Let me know whether you can find the keyboard command!

I have just released a new version though, fixing a few small issues, and introducing a new feature (which lets you toggle between full opacity and what opacity you have configured). Perhaps updating might help?

**Comment by KKacer** [comment]
Nice @niklaskallander 
Sorry for the late reply,
Wasn't a R# user, recently trying to see how it works and whether it can help me or not.
After update and rechecking it, found the command, and working as expected, 
Thank you, and keep going the good job!

**Comment by niklaskallander** [comment]
@KKacer good to hear it's working for you! Closing this. (:
